env:
  global:
    - NDK_VERSION=r10e
language: cpp,android
android:
  components:
    - build-tools-23.0.0
    - android-23
compiler:
 - gcc
 - clang
before_install:
 - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
 - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
 - ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
 - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
 - export PATH=${PATH}:${ANDROID_NDK_HOME}
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install g++-4.8
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
 - cd build
 - mkdir build
 - cd build
 - cmake ..
script: 
 - make
 - pwd
 - cd ../jni/
 - $ANDROID_NDK_HOME/ndk-build -j4

 
